# CMake generated Testfile for 
# Source directory: /home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util
# Build directory: /home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ArrayTraitsTest.CArrayType "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.CArrayType")
set_tests_properties(ArrayTraitsTest.CArrayType PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayNdim "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayNdim")
set_tests_properties(ArrayTraitsTest.ArrayNdim PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayScalarType "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayScalarType")
set_tests_properties(ArrayTraitsTest.ArrayScalarType PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.MakeEigen "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.MakeEigen")
set_tests_properties(ArrayTraitsTest.MakeEigen PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.IsCallable "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.IsCallable")
set_tests_properties(FuncTraitsTest.IsCallable PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgType "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgType")
set_tests_properties(FuncTraitsTest.FuncArgType PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgCount "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgCount")
set_tests_properties(FuncTraitsTest.FuncArgCount PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.UnwrapArgs "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.UnwrapArgs")
set_tests_properties(FuncWrapTest.UnwrapArgs PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.ReturnArrayArg0 "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.ReturnArrayArg0")
set_tests_properties(FuncWrapTest.ReturnArrayArg0 PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
add_test(TupleToolsTest.Slice "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/tuple_tools_test" "--gtest_filter=TupleToolsTest.Slice")
set_tests_properties(TupleToolsTest.Slice PROPERTIES  _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;96;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/python/mujoco/util/CMakeLists.txt;0;")
