# CMake generated Testfile for 
# Source directory: /home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity
# Build directory: /home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PluginTest.ElasticEnergy "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/elasticity_test" "--gtest_filter=PluginTest.ElasticEnergy")
set_tests_properties(PluginTest.ElasticEnergy PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/lib" WORKING_DIRECTORY "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/CMakeLists.txt;31;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.CantileverIntoCircle "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/elasticity_test" "--gtest_filter=PluginTest.CantileverIntoCircle")
set_tests_properties(PluginTest.CantileverIntoCircle PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/lib" WORKING_DIRECTORY "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/CMakeLists.txt;31;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.InvalidTxtAttribute "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/elasticity_test" "--gtest_filter=PluginTest.InvalidTxtAttribute")
set_tests_properties(PluginTest.InvalidTxtAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/lib" WORKING_DIRECTORY "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/CMakeLists.txt;31;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.InvalidMixedAttribute "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/elasticity_test" "--gtest_filter=PluginTest.InvalidMixedAttribute")
set_tests_properties(PluginTest.InvalidMixedAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/lib" WORKING_DIRECTORY "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/CMakeLists.txt;31;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.ValidAttributes "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/bin/elasticity_test" "--gtest_filter=PluginTest.ValidAttributes")
set_tests_properties(PluginTest.ValidAttributes PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/lib" WORKING_DIRECTORY "/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test" _BACKTRACE_TRIPLES "/usr/share/cmake-3.16/Modules/GoogleTest.cmake;353;add_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/CMakeLists.txt;31;gtest_add_tests;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/home/kist-robot2/mujoco-2.3.1_source/mujoco-2.3.1/test/plugin/elasticity/CMakeLists.txt;0;")
